/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class AssetType extends javax.swing.JFrame {

    /**
     * Creates new form AssetType
     */
    public AssetType() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnAssetList = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnAssemble = new javax.swing.JButton();
        btnDirect1 = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnAssetList1 = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();
        btnAssemble1 = new javax.swing.JButton();
        btnDirect2 = new javax.swing.JButton();
        Logout1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnAssetList2 = new javax.swing.JButton();
        btnBack2 = new javax.swing.JButton();
        btnAssemble2 = new javax.swing.JButton();
        btnDirect3 = new javax.swing.JButton();
        Logout2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbAssetType = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnBack3 = new javax.swing.JButton();
        btnAssemble3 = new javax.swing.JButton();
        btnDirect4 = new javax.swing.JButton();
        Logout3 = new javax.swing.JButton();
        btnDirect5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        jPanel3.setBackground(new java.awt.Color(153, 153, 0));
        jPanel3.setForeground(new java.awt.Color(102, 0, 204));
        jPanel3.setLayout(null);

        btnAssetList.setBackground(new java.awt.Color(0, 153, 0));
        btnAssetList.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAssetList.setText("Asset List");
        btnAssetList.setActionCommand("");
        btnAssetList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssetListActionPerformed(evt);
            }
        });
        jPanel3.add(btnAssetList);
        btnAssetList.setBounds(380, 0, 140, 40);

        btnBack.setBackground(new java.awt.Color(0, 153, 0));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel3.add(btnBack);
        btnBack.setBounds(10, 0, 90, 40);

        btnAssemble.setBackground(new java.awt.Color(0, 153, 0));
        btnAssemble.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAssemble.setText("Assemble Asset");
        btnAssemble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssembleActionPerformed(evt);
            }
        });
        jPanel3.add(btnAssemble);
        btnAssemble.setBounds(100, 0, 140, 40);

        btnDirect1.setBackground(new java.awt.Color(0, 153, 0));
        btnDirect1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDirect1.setText("Direct Purchased");
        btnDirect1.setActionCommand("");
        btnDirect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirect1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnDirect1);
        btnDirect1.setBounds(240, 0, 143, 40);

        Logout.setBackground(new java.awt.Color(0, 153, 0));
        Logout.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jPanel3.add(Logout);
        Logout.setBounds(520, 0, 90, 40);

        jPanel4.setBackground(new java.awt.Color(153, 153, 0));
        jPanel4.setForeground(new java.awt.Color(102, 0, 204));
        jPanel4.setLayout(null);

        btnAssetList1.setBackground(new java.awt.Color(0, 153, 0));
        btnAssetList1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAssetList1.setText("Asset List");
        btnAssetList1.setActionCommand("");
        btnAssetList1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssetList1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnAssetList1);
        btnAssetList1.setBounds(380, 0, 140, 40);

        btnBack1.setBackground(new java.awt.Color(0, 153, 0));
        btnBack1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnBack1);
        btnBack1.setBounds(10, 0, 90, 40);

        btnAssemble1.setBackground(new java.awt.Color(0, 153, 0));
        btnAssemble1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAssemble1.setText("Assemble Asset");
        btnAssemble1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssemble1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnAssemble1);
        btnAssemble1.setBounds(100, 0, 140, 40);

        btnDirect2.setBackground(new java.awt.Color(0, 153, 0));
        btnDirect2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDirect2.setText("Direct Purchased");
        btnDirect2.setActionCommand("");
        btnDirect2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirect2ActionPerformed(evt);
            }
        });
        jPanel4.add(btnDirect2);
        btnDirect2.setBounds(240, 0, 143, 40);

        Logout1.setBackground(new java.awt.Color(0, 153, 0));
        Logout1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Logout1.setText("Logout");
        Logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout1ActionPerformed(evt);
            }
        });
        jPanel4.add(Logout1);
        Logout1.setBounds(520, 0, 90, 40);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 80, 1030, 40);

        jPanel5.setBackground(new java.awt.Color(153, 153, 0));
        jPanel5.setForeground(new java.awt.Color(102, 0, 204));
        jPanel5.setLayout(null);

        btnAssetList2.setBackground(new java.awt.Color(0, 153, 0));
        btnAssetList2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAssetList2.setText("Asset List");
        btnAssetList2.setActionCommand("");
        btnAssetList2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssetList2ActionPerformed(evt);
            }
        });
        jPanel5.add(btnAssetList2);
        btnAssetList2.setBounds(380, 0, 140, 40);

        btnBack2.setBackground(new java.awt.Color(0, 153, 0));
        btnBack2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack2.setText("Back");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });
        jPanel5.add(btnBack2);
        btnBack2.setBounds(10, 0, 90, 40);

        btnAssemble2.setBackground(new java.awt.Color(0, 153, 0));
        btnAssemble2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAssemble2.setText("Assemble Asset");
        btnAssemble2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssemble2ActionPerformed(evt);
            }
        });
        jPanel5.add(btnAssemble2);
        btnAssemble2.setBounds(100, 0, 140, 40);

        btnDirect3.setBackground(new java.awt.Color(0, 153, 0));
        btnDirect3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDirect3.setText("Direct Purchased");
        btnDirect3.setActionCommand("");
        btnDirect3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirect3ActionPerformed(evt);
            }
        });
        jPanel5.add(btnDirect3);
        btnDirect3.setBounds(240, 0, 143, 40);

        Logout2.setBackground(new java.awt.Color(0, 153, 0));
        Logout2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Logout2.setText("Logout");
        Logout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout2ActionPerformed(evt);
            }
        });
        jPanel5.add(Logout2);
        Logout2.setBounds(520, 0, 90, 40);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1220, 710));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Select Asset Type");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 230, 340, 70);

        cmbAssetType.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cmbAssetType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Direct Purchased Assets", "Assembled Assets" }));
        cmbAssetType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAssetTypeActionPerformed(evt);
            }
        });
        getContentPane().add(cmbAssetType);
        cmbAssetType.setBounds(610, 230, 300, 100);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spine-fixed-asset.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 100, 870, 400);

        jPanel6.setBackground(new java.awt.Color(153, 153, 0));
        jPanel6.setForeground(new java.awt.Color(102, 0, 204));
        jPanel6.setLayout(null);

        btnBack3.setBackground(new java.awt.Color(0, 153, 0));
        btnBack3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack3.setText("Back");
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });
        jPanel6.add(btnBack3);
        btnBack3.setBounds(10, 0, 90, 40);

        btnAssemble3.setBackground(new java.awt.Color(0, 153, 0));
        btnAssemble3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAssemble3.setText("Assemble Asset");
        btnAssemble3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssemble3ActionPerformed(evt);
            }
        });
        jPanel6.add(btnAssemble3);
        btnAssemble3.setBounds(100, 0, 140, 40);

        btnDirect4.setBackground(new java.awt.Color(0, 153, 0));
        btnDirect4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDirect4.setText("Working Progress");
        btnDirect4.setActionCommand("");
        btnDirect4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirect4ActionPerformed(evt);
            }
        });
        jPanel6.add(btnDirect4);
        btnDirect4.setBounds(380, 0, 160, 40);

        Logout3.setBackground(new java.awt.Color(0, 153, 0));
        Logout3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Logout3.setText("Logout");
        Logout3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout3ActionPerformed(evt);
            }
        });
        jPanel6.add(Logout3);
        Logout3.setBounds(540, 0, 90, 40);

        btnDirect5.setBackground(new java.awt.Color(0, 153, 0));
        btnDirect5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDirect5.setText("Direct Purchased");
        btnDirect5.setActionCommand("");
        btnDirect5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirect5ActionPerformed(evt);
            }
        });
        jPanel6.add(btnDirect5);
        btnDirect5.setBounds(240, 0, 143, 40);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 80, 1120, 40);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("ASSET TYPE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(420, -10, 250, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1120, 260);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 320, 1130, 280);

        setSize(new java.awt.Dimension(1136, 637));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAssetTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAssetTypeActionPerformed
        // TODO add your handling code here:
        
        if(cmbAssetType.getSelectedIndex()==0)
        { new DirectPurchasedAsset().setVisible(true);
           this.dispose();
        }
        else if(cmbAssetType.getSelectedIndex()==1)
        {
            new AssembleAsset().setVisible(true);
            this.dispose();
        
        }
           
    }//GEN-LAST:event_cmbAssetTypeActionPerformed

    private void btnAssetListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssetListActionPerformed
        new AssetList().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAssetListActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new AssetType().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAssembleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssembleActionPerformed
        new AssembleAsset().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAssembleActionPerformed

    private void btnDirect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirect1ActionPerformed
        new DirectPurchasedAsset().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDirect1ActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        new signup().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void btnAssetList1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssetList1ActionPerformed
        new AssetList().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAssetList1ActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        new AssetType().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnAssemble1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssemble1ActionPerformed
        new AssembleAsset().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAssemble1ActionPerformed

    private void btnDirect2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirect2ActionPerformed
        new DirectPurchasedAsset().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDirect2ActionPerformed

    private void Logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout1ActionPerformed
        new signup().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Logout1ActionPerformed

    private void btnAssetList2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssetList2ActionPerformed
        new AssetList().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAssetList2ActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        new AssetType().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void btnAssemble2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssemble2ActionPerformed
        new AssembleAsset().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAssemble2ActionPerformed

    private void btnDirect3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirect3ActionPerformed
        new DirectPurchasedAsset().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDirect3ActionPerformed

    private void Logout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout2ActionPerformed
        new signup().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Logout2ActionPerformed

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        new AssetType().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBack3ActionPerformed

    private void btnAssemble3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssemble3ActionPerformed
        new AssembleAsset().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAssemble3ActionPerformed

    private void btnDirect4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirect4ActionPerformed
        new workingProgress().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDirect4ActionPerformed

    private void Logout3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout3ActionPerformed
        new signup().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Logout3ActionPerformed

    private void btnDirect5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirect5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDirect5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssetType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssetType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssetType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssetType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssetType().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton Logout1;
    private javax.swing.JButton Logout2;
    private javax.swing.JButton Logout3;
    private javax.swing.JButton btnAssemble;
    private javax.swing.JButton btnAssemble1;
    private javax.swing.JButton btnAssemble2;
    private javax.swing.JButton btnAssemble3;
    private javax.swing.JButton btnAssetList;
    private javax.swing.JButton btnAssetList1;
    private javax.swing.JButton btnAssetList2;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnDirect1;
    private javax.swing.JButton btnDirect2;
    private javax.swing.JButton btnDirect3;
    private javax.swing.JButton btnDirect4;
    private javax.swing.JButton btnDirect5;
    private javax.swing.JComboBox cmbAssetType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
