import MyClasses.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class AssembleAsset extends javax.swing.JFrame {
          Database db = new Database();
          String asNo;
          String asName;
          String Category;
          String lifetime;
    /**
     * Creates new form AssembleAsset
     */
    public AssembleAsset() {
        initComponents();
        geAssetNo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLifeTime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAssetNo = new javax.swing.JTextField();
        txtAssetName = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        workigchrgs = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnAssemble = new javax.swing.JButton();
        btnDirect1 = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        btnDirect4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("ASSEMBLE ASSET");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 20, 360, 70);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Life Time");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 370, 80, 40);
        getContentPane().add(txtLifeTime);
        txtLifeTime.setBounds(410, 370, 250, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Asset No");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 150, 80, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Asset Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 220, 100, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Category");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(270, 290, 80, 40);
        getContentPane().add(txtAssetNo);
        txtAssetNo.setBounds(410, 150, 250, 40);
        getContentPane().add(txtAssetName);
        txtAssetName.setBounds(410, 220, 250, 40);

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BUILDING", "MACHING", "OTHER" }));
        cmbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCategory);
        cmbCategory.setBounds(410, 290, 250, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });
        jPanel2.setLayout(null);

        workigchrgs.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        workigchrgs.setForeground(new java.awt.Color(0, 0, 204));
        workigchrgs.setText("Click here to complete charges of Working Progress");
        workigchrgs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workigchrgsMouseClicked(evt);
            }
        });
        jPanel2.add(workigchrgs);
        workigchrgs.setBounds(10, 10, 610, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(230, 460, 620, 70);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(102, 0, 204));

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAssemble.setBackground(new java.awt.Color(153, 153, 153));
        btnAssemble.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAssemble.setText("Assemble Asset");
        btnAssemble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssembleActionPerformed(evt);
            }
        });

        btnDirect1.setBackground(new java.awt.Color(153, 153, 153));
        btnDirect1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDirect1.setText("Direct Purchased");
        btnDirect1.setActionCommand("");
        btnDirect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirect1ActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(153, 153, 153));
        Logout.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        btnDirect4.setBackground(new java.awt.Color(0, 153, 0));
        btnDirect4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDirect4.setText("Working Progress");
        btnDirect4.setActionCommand("");
        btnDirect4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirect4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnAssemble, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(btnDirect1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(btnDirect4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnDirect1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnAssemble, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnDirect4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 90, 1010, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/business-intelligence-bg.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1010, 660);

        setSize(new java.awt.Dimension(1025, 704));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseEntered

    private void cmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoryActionPerformed

    private void workigchrgsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workigchrgsMouseClicked
       db.connection();
     
      if(txtAssetName.getText().equals("") ){
       JOptionPane.showMessageDialog(null,"Please Fill AssetName");
      } 
      else if(txtLifeTime.getText().equals("") ){
       JOptionPane.showMessageDialog(null,"Please Fill LifeTime");
      } 
       else if(Integer.parseInt(txtLifeTime.getText())<0.0){
           JOptionPane.showMessageDialog(null,"Life Time should be Positive number");
         }
      else{
       String assetNo = txtAssetNo.getText();
        String assetName = txtAssetName.getText();
        String category = (String) cmbCategory.getSelectedItem();
        //String assembleDate = date;
        String lifeTime = txtLifeTime.getText();
        
         //String sql = String.format("INSERT INTO working_progress(AssetNo,AssetName,category,LifeTime)VALUES('%s','%s','%s','%s')"
          //      ,assetNo,assetName,category,lifeTime);
         lifetime = lifeTime;
         Category = category;
         asName = assetName;
        //  int i = db.updateQuery(sql);
     //   if(i>0)
         JOptionPane.showMessageDialog(null,"successfully added");
           new workingProgress(asNo,asName,Category,lifetime).setVisible(true);
           txtAssetName.setText(null);
           txtLifeTime.setText(null);
       this.dispose();
        
        //else
       // { JOptionPane.showMessageDialog(null,"Not entered");
       // }
        
        
      }
    }//GEN-LAST:event_workigchrgsMouseClicked
   
    public  void geAssetNo()
    {
        db.connection();
        ResultSet rs;
        String sql = "SELECT * FROM working_progress ORDER BY AssetNo DESC LIMIT 1";
        rs = db.selectQuery(sql);
        try {
            while(rs.next())
            {
                String a = (rs.getString(1));
                int value = Integer.parseInt(a.replaceAll("[^0-9]", ""));
                value = value + 1;
                String res = "A" + value;
               txtAssetNo.setText(res);
               asNo = res;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"SQL ERROR! " + ex.getMessage());   
        }
                
    }
    
   
   
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new AssetType().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAssembleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssembleActionPerformed
        new AssembleAsset().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAssembleActionPerformed

    private void btnDirect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirect1ActionPerformed
        new DirectPurchasedAsset().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDirect1ActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        new signup().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void btnDirect4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirect4ActionPerformed
        new workingProgress().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDirect4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssembleAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssembleAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssembleAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssembleAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssembleAsset().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton btnAssemble;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDirect1;
    private javax.swing.JButton btnDirect4;
    private javax.swing.JComboBox cmbCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAssetName;
    private javax.swing.JTextField txtAssetNo;
    private javax.swing.JTextField txtLifeTime;
    private javax.swing.JLabel workigchrgs;
    // End of variables declaration//GEN-END:variables
}
