
import MyClasses.Database;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class AssembleFurtherDet extends javax.swing.JFrame {
                   Database db = new Database();
    /**
     * Creates new form AssembleFurtherDet
     */
    public AssembleFurtherDet() {
        initComponents();
        loadAssetNo();
      //  showAssetName();
    }
    
    
      public void loadAssetNo()
    {
         ResultSet rs;
        db.connection();
         try {
            String sql = "SELECT AssetNo FROM assemble_asset";
            rs = db.selectQuery(sql);
        while (rs.next()) {
            String pat = rs.getString(1);
            cmbAssetNo.addItem(pat);
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbAssetNo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Select Asset No.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 50, 190, 60);

        cmbAssetNo.setBackground(new java.awt.Color(153, 153, 153));
        cmbAssetNo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAssetNoItemStateChanged(evt);
            }
        });
        cmbAssetNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbAssetNoMouseClicked(evt);
            }
        });
        cmbAssetNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAssetNoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbAssetNo);
        cmbAssetNo.setBounds(550, 60, 180, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Asset No", "Material Name", "Qty", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 150, 780, 430);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 40, 120, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tecnografica-wallpapers-1-1400x660.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1010, 620);

        setSize(new java.awt.Dimension(1019, 664));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         new AssembledAssetList().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbAssetNoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbAssetNoItemStateChanged
        db.connection();
        ResultSet rs;
        String asset_no = String.valueOf(cmbAssetNo.getSelectedItem());
        String sql = String.format("SELECT * FROM material_master_table WHERE AssetNo = '%s'",asset_no);
   try{
            rs = db.selectQuery(sql);
           DefaultTableModel mode2 =  (DefaultTableModel) jTable1.getModel();
        mode2.setRowCount(0);
            while(rs.next())
            {   
              
               
                // jTable1.setModel(new  DefaultTableModel(null,new String[]{"AssetNo","date","details","price"}) );
                 String AssetNo = rs.getString("AssetNo");
                 String MaterialName = rs.getString("materialName");
                 String Qty = rs.getString("Qty");
                 String price = rs.getString("price");
               
                 
                
             
                     DefaultTableModel model =  (DefaultTableModel) jTable1.getModel();
                
                 Object[] content = {AssetNo,MaterialName,Qty,price};
       
           
       
                 model.addRow(content);
        
            
        
            }  
     
    }
        
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_cmbAssetNoItemStateChanged

    public void showAssetName(){
       db.connection();
        ResultSet rs;
          int rows = jTable1.getRowCount();
           for(int row = 0; row<rows; row++){
          String asset_no = String.valueOf(cmbAssetNo.getSelectedItem());
        String sql = String.format("SELECT AssetName FROM assemble_asset WHERE AssetNo = '%s'",asset_no);
      
          try{
            rs = db.selectQuery(sql);
            while(rs.next())
            {   // jTable1.setModel(new  DefaultTableModel(null,new String[]{"AssetNo","date","details","price"}) );
                 String AssetName = rs.getString("AssetName");
                
                
                
                  DefaultTableModel model =  (DefaultTableModel) jTable1.getModel();
        model.setValueAt(AssetName, row, 1);
         //  model.removeTableModelListener(jTable1);
       
        
            }  //jTable1.setModel(new  DefaultTableModel(null,new String[]{"AssetNo","date","details","price"}) );
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }}
    private void cmbAssetNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAssetNoActionPerformed
       
    }//GEN-LAST:event_cmbAssetNoActionPerformed

    private void cmbAssetNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbAssetNoMouseClicked
                   DefaultTableModel model =  (DefaultTableModel) jTable1.getModel();
                  Object[] content = {"","","","",""};
    }//GEN-LAST:event_cmbAssetNoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssembleFurtherDet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssembleFurtherDet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssembleFurtherDet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssembleFurtherDet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssembleFurtherDet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbAssetNo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
