import MyClasses.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class DirectPurchasedAsset extends javax.swing.JFrame {
                      Database db = new Database();
    /**
     * Creates new form DirectPurchasedAsset
     */
    public DirectPurchasedAsset() {
        initComponents();
        geAssetNo();
    }

     public  void geAssetNo()
    {
        db.connection();
        ResultSet rs;
        String sql = "SELECT * FROM direct_purchased ORDER BY AssetNo DESC LIMIT 1";
        rs = db.selectQuery(sql);
        try {
            while(rs.next())
            {
                String a = (rs.getString(1));
                int value = Integer.parseInt(a.replaceAll("[^0-9]", ""));
                value = value + 1;
                String res = "D" + value;
              txtAssetNo.setText(res);
               
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"SQL ERROR! " + ex.getMessage());   
        }
                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtAssetNo = new javax.swing.JTextField();
        txtAssetName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtLifeTime = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        btnAddAssetList = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnAssemble = new javax.swing.JButton();
        btnDirect1 = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtPurchasedDate = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("AssetNo ");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(274, 170, 110, 40);

        txtAssetNo.setName("Assetno"); // NOI18N
        getContentPane().add(txtAssetNo);
        txtAssetNo.setBounds(440, 170, 270, 30);

        txtAssetName.setName("AssetName"); // NOI18N
        txtAssetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAssetNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtAssetName);
        txtAssetName.setBounds(440, 230, 270, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Price");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(320, 350, 70, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Category");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 290, 150, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Asset Name ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 230, 160, 40);

        txtPrice.setName("Price"); // NOI18N
        getContentPane().add(txtPrice);
        txtPrice.setBounds(440, 350, 270, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Date Of purchased");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(180, 400, 230, 40);

        txtLifeTime.setName("lifeTime"); // NOI18N
        getContentPane().add(txtLifeTime);
        txtLifeTime.setBounds(440, 470, 270, 30);

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VEHICALE", "MACHING", "PROPERTIES", "EQUIPMENTS", "OTHERS" }));
        cmbCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(cmbCategory);
        cmbCategory.setBounds(440, 290, 270, 40);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel4.setText("DIRECT PURCHASED");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 0, 430, 80);

        btnAddAssetList.setBackground(new java.awt.Color(204, 0, 204));
        btnAddAssetList.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAddAssetList.setText("Add to the Asset List");
        btnAddAssetList.setActionCommand("");
        btnAddAssetList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddAssetList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAssetListActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddAssetList);
        btnAddAssetList.setBounds(740, 500, 240, 60);

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));
        jPanel1.setForeground(new java.awt.Color(102, 0, 204));
        jPanel1.setLayout(null);

        btnBack.setBackground(new java.awt.Color(0, 153, 0));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(10, 0, 90, 40);

        btnAssemble.setBackground(new java.awt.Color(0, 153, 0));
        btnAssemble.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAssemble.setText("Assemble Asset");
        btnAssemble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssembleActionPerformed(evt);
            }
        });
        jPanel1.add(btnAssemble);
        btnAssemble.setBounds(190, 0, 140, 40);

        btnDirect1.setBackground(new java.awt.Color(0, 153, 0));
        btnDirect1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDirect1.setText("Direct Purchased");
        btnDirect1.setActionCommand("");
        btnDirect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirect1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnDirect1);
        btnDirect1.setBounds(430, 0, 143, 40);

        Logout.setBackground(new java.awt.Color(0, 153, 0));
        Logout.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jPanel1.add(Logout);
        Logout.setBounds(680, 0, 90, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 70, 1040, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Life Time");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(290, 480, 120, 29);
        getContentPane().add(txtPurchasedDate);
        txtPurchasedDate.setBounds(440, 410, 270, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coins-currency-investment-insurance-e1507223372878.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1030, 600);

        setSize(new java.awt.Dimension(1050, 647));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAssetListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAssetListActionPerformed
        db.connection();
        
        if(txtAssetName.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Please enter Asset Name ");
          }
        
        else if(txtPrice.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Please enter Price");
          }
         else if(txtLifeTime.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Please enter Life Time");
          }
        
         else if(txtPurchasedDate.getDate().equals("")){
        JOptionPane.showMessageDialog(null,"Please choose a Date");
          }
         else if(Integer.parseInt(txtLifeTime.getText())<0.0){
           JOptionPane.showMessageDialog(null,"Life Time should be Positive number");
         }
         else if(((txtPrice.getText().trim().matches("[a-zA-z,]+"))))
          {  JOptionPane.showMessageDialog(null,"Price should only contains numbers ");} 
         
         else{
         SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
       String date = sdf.format(txtPurchasedDate.getDate());
       
        String assetNo = txtAssetNo.getText();
        String assetName = txtAssetName.getText();
        String category = (String) cmbCategory.getSelectedItem();
        String price = txtPrice.getText();
        String DateOfPurch = date;
        String lifeTime = txtLifeTime.getText();
        
        String sql = String.format("INSERT INTO direct_purchased(AssetNo,AssetName,category,price,purchased_date,Life_Time)VALUES('%s','%s','%s','%s','%s','%s')"
                ,assetNo,assetName,category,price,DateOfPurch,lifeTime);
     
        int i = db.updateQuery(sql);
        if(i>0)
        { JOptionPane.showMessageDialog(null,"successfully added");
           txtAssetName.setText(null);
           txtPrice.setText(null);
           txtPurchasedDate.setDate(null);
           txtLifeTime.setText(null);
        }
        else
        { JOptionPane.showMessageDialog(null,"Not entered");
        }
        
         }
    }//GEN-LAST:event_btnAddAssetListActionPerformed

    public void sendAssetList()
    {   db.connection();
    
     SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
       String date = sdf.format(txtPurchasedDate.getDate());
    
     String assetNo = txtAssetNo.getText();
        String assetName = txtAssetName.getText();
        String category = (String) cmbCategory.getSelectedItem();
        String price = txtPrice.getText();
        String DateOfPurch = date;
        String lifeTime = txtLifeTime.getText();
     
       String sql = String.format("INSERT INTO asset_master_table(AssetNo,AssetName,Date,Category,price)VALUES('%s','%s','%s','%s','%s','%s')"
                ,assetNo,assetName,category,price,DateOfPurch,lifeTime);
       
     int i = db.updateQuery(sql);
        if(i>0)
        { JOptionPane.showMessageDialog(null,"successfully added to the Master List");
            new AssetList().setVisible(true);
        this.dispose();
        }
        else
        { JOptionPane.showMessageDialog(null,"Not entered Matser List");
        }
    
       }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new AssetType().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAssembleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssembleActionPerformed
       new AssembleAsset().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAssembleActionPerformed

    private void btnDirect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirect1ActionPerformed
        new DirectPurchasedAsset().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDirect1ActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        new signup().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void txtAssetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAssetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAssetNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DirectPurchasedAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DirectPurchasedAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DirectPurchasedAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DirectPurchasedAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DirectPurchasedAsset().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton btnAddAssetList;
    private javax.swing.JButton btnAssemble;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDirect1;
    private javax.swing.JComboBox cmbCategory;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAssetName;
    private javax.swing.JTextField txtAssetNo;
    private javax.swing.JTextField txtLifeTime;
    private javax.swing.JTextField txtPrice;
    private com.toedter.calendar.JDateChooser txtPurchasedDate;
    // End of variables declaration//GEN-END:variables
}
