
import MyClasses.Database;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class DirectPurchasedAssetList extends javax.swing.JFrame {
                 Database db = new Database();
    /**
     * Creates new form DirectPurchasedAssetList
     */
    public DirectPurchasedAssetList() {
        initComponents();
        showTable();
        ShowOndayTBLDetails();
         ShowAnydayTBLDetails();
         
        Date();
    }

    
     public void showTable(){

 try{  db.connection();   
     ResultSet rs1;
    String sql = "SELECT AssetNo,AssetName,purchased_date,Life_Time,price FROM direct_purchased";
     rs1 = db.selectQuery(sql);
 
        
    while(rs1.next())
        
    {  String AssetNo = rs1.getString("AssetNo");
       String AssetName = rs1.getString("AssetName");
       String PurchasedDate = rs1.getString("purchased_date");
       String lifeTime = rs1.getString("Life_Time");
       String price = rs1.getString("price");
      
       
       
       Object[] content = {AssetNo,AssetName,PurchasedDate,lifeTime,price};
       
       DefaultTableModel model =  (DefaultTableModel) jTable4.getModel();
       
       model.addRow(content);
      
       
    
      }
    
    
  }
  catch(Exception e){
  JOptionPane.showMessageDialog(null, e.getMessage());
  
     }
      }
     
      public void Date(){
         int rows = jTbleOnday.getRowCount();
       for(int row = 0; row<rows; row++){
        String pattern = "yyyy-MM-30";
       SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
       String date = simpleDateFormat.format(new Date());
       
       DefaultTableModel model =  (DefaultTableModel)jTbleOnday.getModel();
        model.setValueAt(date, row, 2);
       }
     }
      
      public void ShowOndayTBLDetails(){
      int rows = jTable4.getRowCount();
      for(int row = 0; row<rows; row++)
     { 
       String AssetNo = (String)jTable4.getValueAt(row, 0);
       String AssetName = (String)jTable4.getValueAt(row, 1);
       
        DefaultTableModel model =  (DefaultTableModel)jTbleOnday.getModel();
                
                 Object[] content = {AssetNo, AssetName};
       
                 model.addRow(content);
     
     
        }}
        public void ShowAnydayTBLDetails(){
      int rows = jTable4.getRowCount();
      for(int row = 0; row<rows; row++)
     { 
       String AssetNo = (String)jTable4.getValueAt(row, 0);
       String AssetName = (String)jTable4.getValueAt(row, 1);
       
        DefaultTableModel model =  (DefaultTableModel)jTbleAnyday.getModel();
                
                 Object[] content = {AssetNo, AssetName};
       
                 model.addRow(content);
     
     
        }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCalTotDep1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnAssetList4 = new javax.swing.JButton();
        btnBack6 = new javax.swing.JButton();
        Logout4 = new javax.swing.JButton();
        btnAssemble1 = new javax.swing.JButton();
        btnDirect1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTbleOnday = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTbleAnyday = new javax.swing.JTable();
        btnCalTotDep = new javax.swing.JButton();
        btnCalTotDep2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnCalTotDep3 = new javax.swing.JButton();
        DteChoser1 = new com.toedter.calendar.JDateChooser();
        jTextField2 = new javax.swing.JTextField();
        btnCalDep = new javax.swing.JButton();
        btnCalDep2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        btnCalTotDep1.setBackground(new java.awt.Color(0, 153, 153));
        btnCalTotDep1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnCalTotDep1.setText("Calculate Total Depreciate");
        btnCalTotDep1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalTotDep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalTotDep1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setForeground(new java.awt.Color(102, 0, 204));
        jPanel5.setLayout(null);

        btnAssetList4.setBackground(new java.awt.Color(153, 153, 153));
        btnAssetList4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAssetList4.setText("Asset List");
        btnAssetList4.setActionCommand("");
        btnAssetList4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssetList4ActionPerformed(evt);
            }
        });
        jPanel5.add(btnAssetList4);
        btnAssetList4.setBounds(820, 0, 140, 40);

        btnBack6.setBackground(new java.awt.Color(153, 153, 153));
        btnBack6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack6.setText("Back");
        btnBack6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack6ActionPerformed(evt);
            }
        });
        jPanel5.add(btnBack6);
        btnBack6.setBounds(10, 0, 90, 40);

        Logout4.setBackground(new java.awt.Color(153, 153, 153));
        Logout4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Logout4.setText("Logout");
        Logout4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout4ActionPerformed(evt);
            }
        });
        jPanel5.add(Logout4);
        Logout4.setBounds(1070, 0, 90, 40);

        btnAssemble1.setBackground(new java.awt.Color(153, 153, 153));
        btnAssemble1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAssemble1.setText("Assemble Asset List");
        btnAssemble1.setActionCommand("Assemble Asset list");
        btnAssemble1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssemble1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnAssemble1);
        btnAssemble1.setBounds(210, 0, 163, 40);

        btnDirect1.setBackground(new java.awt.Color(153, 153, 153));
        btnDirect1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDirect1.setText("Direct Purchased List");
        btnDirect1.setActionCommand("");
        btnDirect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirect1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnDirect1);
        btnDirect1.setBounds(500, 0, 190, 40);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 60, 1240, 40);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Direct Purchased Assets List");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 3, 540, 47);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AssetNo", "AssetName", "DateOfPurchased", "Life Time", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable4);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 110, 740, 260);

        jTbleOnday.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AssetNo", "Asset Name", "DepriciateDate", "Depreciate Amount"
            }
        ));
        jScrollPane3.setViewportView(jTbleOnday);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 440, 570, 210);

        jTbleAnyday.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AssetNo", "Asset Name", "Depreciate Amount"
            }
        ));
        jScrollPane2.setViewportView(jTbleAnyday);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(690, 440, 510, 210);

        btnCalTotDep.setBackground(new java.awt.Color(0, 153, 153));
        btnCalTotDep.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnCalTotDep.setText("Calculate Total Depreciate");
        btnCalTotDep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalTotDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalTotDepActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalTotDep);
        btnCalTotDep.setBounds(40, 770, 210, 50);

        btnCalTotDep2.setBackground(new java.awt.Color(0, 153, 153));
        btnCalTotDep2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnCalTotDep2.setText("Calculate Total Depreciate");
        btnCalTotDep2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalTotDep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalTotDep2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalTotDep2);
        btnCalTotDep2.setBounds(40, 770, 210, 50);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setText("Total Depreciate Amount");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(250, 660, 220, 30);

        btnCalTotDep3.setBackground(new java.awt.Color(0, 153, 153));
        btnCalTotDep3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnCalTotDep3.setText("Calculate Total Depreciate");
        btnCalTotDep3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalTotDep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalTotDep3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalTotDep3);
        btnCalTotDep3.setBounds(40, 770, 210, 50);
        getContentPane().add(DteChoser1);
        DteChoser1.setBounds(950, 370, 250, 40);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(490, 660, 100, 30);

        btnCalDep.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btnCalDep.setText("Calculate Total Depreciate");
        btnCalDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalDepActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalDep);
        btnCalDep.setBounds(20, 660, 210, 40);

        btnCalDep2.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btnCalDep2.setText("Calculate Total Depreciate");
        btnCalDep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalDep2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalDep2);
        btnCalDep2.setBounds(690, 660, 210, 40);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setText("Total Depreciate Amount");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(910, 650, 210, 40);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Select a Date");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(820, 380, 120, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(1110, 660, 90, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WAste-Recycler-banner-5.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 100, 1250, 490);

        setSize(new java.awt.Dimension(1251, 763));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssetList4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssetList4ActionPerformed
        new AssetList().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAssetList4ActionPerformed

    private void btnBack6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack6ActionPerformed
        new admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBack6ActionPerformed

    private void Logout4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout4ActionPerformed
        new signup().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Logout4ActionPerformed

    private void btnAssemble1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssemble1ActionPerformed
        new AssembledAssetList().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAssemble1ActionPerformed

    private void btnDirect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirect1ActionPerformed
        new DirectPurchasedAssetList().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDirect1ActionPerformed

    private void btnCalTotDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalTotDepActionPerformed

    }//GEN-LAST:event_btnCalTotDepActionPerformed

    private void btnCalTotDep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalTotDep1ActionPerformed

    }//GEN-LAST:event_btnCalTotDep1ActionPerformed

    private void btnCalTotDep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalTotDep2ActionPerformed
      
    }//GEN-LAST:event_btnCalTotDep2ActionPerformed

    private void btnCalTotDep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalTotDep3ActionPerformed
       
    }//GEN-LAST:event_btnCalTotDep3ActionPerformed

    private void btnCalDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalDepActionPerformed
 
        
        
           DefaultTableModel model =  (DefaultTableModel)jTable4.getModel();
        int rows = jTable4.getRowCount();
          double tot = 0.0;
        try{
       for(int row=0;row<=rows;row++){
       
        String lifetime = (String) model.getValueAt(row, 3);
    int lifetimei = Integer.parseInt(lifetime );
    String price =  (String) model.getValueAt(row, 4);
    double pricei = Double.parseDouble(price);
    String date =  (String)model.getValueAt(row, 2);
    DefaultTableModel model2 =  (DefaultTableModel)jTbleOnday.getModel();
    String Depdate = (String)model2.getValueAt(row, 2);
    
    DateFormat formatter;
    Date dd1;
    Date dd2;
    formatter = new SimpleDateFormat("yyyy-MM-dd");
   
    dd1 = (Date)formatter.parse(date);
    dd2 = (Date)formatter.parse(Depdate);  
    
     long diff = dd2.getTime() - dd1.getTime();
   
   long sec = diff / 1000 % 60;
   long min = diff/(60*1000) % 60;
   long hours = diff /(60*60*1000);
   long days = hours/24;
   long months = days/30;
  
   
     double amt;
    
      
       amt =((pricei/(lifetimei*365))*days) ;
    double roundAmt = Math.round(amt*100)/100;
    String roundAmtS = String.valueOf(roundAmt);
    
     
     model2.setValueAt(roundAmtS, row, 3);
     
     tot=tot+roundAmt;
     String tots = String.valueOf(tot);
   jTextField2.setText(tots);
       }
    
        }
        
         catch(Exception e)
     {// JOptionPane.showMessageDialog(this,e.getMessage());
       
     } 
          db.connection();
           
        try{
        int rown= jTable4.getRowCount();
       
        for(int row = 0; row<rown; row++)
     { 
       String AssetNo = (String)jTable4.getValueAt(row, 0);
       String AssetName = (String)jTable4.getValueAt(row, 1);
       String date = (String)jTable4.getValueAt(row, 2); 
       String lifeTime = (String)jTable4.getValueAt(row, 3); 
       String price = (String)jTable4.getValueAt(row, 4);
       String DepDate = (String)jTbleOnday.getValueAt(row, 2);
       String DepAmt = (String)jTbleOnday.getValueAt(row, 3);
       String DepAmount = String.valueOf(DepAmt) ;
       String Category = "Direct Purchased";
       
     //  String wrkngPRogNo = jTextField2.getText();
       String sql = "INSERT INTO depriciated_direct_assetlist(AssetNo,AssetName,category,price,purchased_date,Life_Time,Depriciate_Date,Depriciate_Amt) VALUES('"+AssetNo+"','"+AssetName+"','"+Category+"','"+price+"','"+date+"','"+lifeTime+"','"+DepDate+"','"+DepAmount+"')";
      
    
         int i = db.updateQuery(sql);
       
        if(i<0)
        { JOptionPane.showMessageDialog(null,"Not entered");
           
            }
        }
         JOptionPane.showMessageDialog(null,"Successfully added!");}
         catch(Exception e)
     { JOptionPane.showMessageDialog(this,e.getMessage());
       
     } 
        
        
        
    }//GEN-LAST:event_btnCalDepActionPerformed

    private void btnCalDep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalDep2ActionPerformed
       
         DefaultTableModel model =  (DefaultTableModel)jTable4.getModel();
        int rows = jTable4.getRowCount();
         double tot=0.0;
        try{
       for(int row=0;row<=rows;row++){
       
        String lifetime = (String) model.getValueAt(row, 3);
    int lifetimei = Integer.parseInt(lifetime );
    String price =  (String) model.getValueAt(row, 4);
    double pricei = Double.parseDouble(price);
    String date =  (String)model.getValueAt(row, 2);
    
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
       String Depdate = sdf.format(DteChoser1.getDate());
       
    DefaultTableModel model2 =  (DefaultTableModel)jTbleAnyday.getModel();
   // String Depdatei = (String)model2.getValueAt(row, 2);
    
    DateFormat formatter;
    Date dd1;
    Date dd2;
    formatter = new SimpleDateFormat("yyyy-MM-dd");
   
    dd1 = (Date)formatter.parse(date);
    dd2 = (Date)formatter.parse(Depdate);  
    
     long diff = dd2.getTime() - dd1.getTime();
   
   long sec = diff / 1000 % 60;
   long min = diff/(60*1000) % 60;
   long hours = diff /(60*60*1000);
   long days = hours/24;
   long months = days/30;
   //JOptionPane.showMessageDialog(null,days );
   
     double amt;
     
      
       amt =((pricei/(lifetimei*365))*days) ;
    double roundAmt = Math.round(amt*100)/100;
    String roundAmtS = String.valueOf(roundAmt);
    
     
     model2.setValueAt(roundAmtS, row, 2);
     
    
        tot=tot+roundAmt;
     String tots = String.valueOf(tot);
  jTextField1.setText(tots);
     
    /* int Deprows = jTbleAnyday.getRowCount();
      for(int rw=0;rw<=Deprows;rw++){
           String depAmt =  (String) model2.getValueAt(rw, 2);
           double depamtd = Double.valueOf(depAmt);
     tot=tot+depamtd;
     String tots = String.valueOf(tot);
    jTextField1.setText(tots);}*/
       }
       
       
        
        }
        
         catch(Exception e)
     {// JOptionPane.showMessageDialog(this,e.getMessage());
       
     }      
    }//GEN-LAST:event_btnCalDep2ActionPerformed

    public void CalAnyDayTot(){
        DefaultTableModel model2 =  (DefaultTableModel)jTbleAnyday.getModel();
        double tot=0.0;
      int Deprows = jTbleAnyday.getRowCount();
      for(int rw=0;rw<=Deprows;rw++){
           String depAmt =  (String) model2.getValueAt(rw, 2);
           double depamtd = Double.valueOf(depAmt);
     tot=tot+depamtd;
     String tots = String.valueOf(tot);
    jTextField1.setText(tots);}
      }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DirectPurchasedAssetList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DirectPurchasedAssetList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DirectPurchasedAssetList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DirectPurchasedAssetList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DirectPurchasedAssetList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DteChoser1;
    private javax.swing.JButton Logout4;
    private javax.swing.JButton btnAssemble1;
    private javax.swing.JButton btnAssetList4;
    private javax.swing.JButton btnBack6;
    private javax.swing.JButton btnCalDep;
    private javax.swing.JButton btnCalDep2;
    private javax.swing.JButton btnCalTotDep;
    private javax.swing.JButton btnCalTotDep1;
    private javax.swing.JButton btnCalTotDep2;
    private javax.swing.JButton btnCalTotDep3;
    private javax.swing.JButton btnDirect1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable jTable4;
    private javax.swing.JTable jTbleAnyday;
    private javax.swing.JTable jTbleOnday;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
