
import MyClasses.Database;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class dispose extends javax.swing.JFrame {
               Database db = new Database();
    /**
     * Creates new form dispose
     */
    public dispose() {
        initComponents();
        loadAssembleNo();
        loadDirectpurchsdNo();
        getDirectDetails();
    }

    
    public void loadAssembleNo()
    {
         ResultSet rs;
        db.connection();
         try {
            String sql = "SELECT AssetNo FROM assemble_asset";
            rs = db.selectQuery(sql);
        while (rs.next()) {
            String pat = rs.getString(1);
            cmbAssetNo.addItem(pat);
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e);
    }
    }
    
     public void loadDirectpurchsdNo()
    {
         ResultSet rs;
        db.connection();
         try {
            String sql = "SELECT AssetNo FROM direct_purchased";
            rs = db.selectQuery(sql);
        while (rs.next()) {
            String pat = rs.getString(1);
            cmbAssetNo.addItem(pat);
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e);
    }
    }
     
     public void getDirectDetails(){
     
       db.connection();
        ResultSet rs;  
        String asset_no = String.valueOf(cmbAssetNo.getSelectedItem());
        String sql = String.format("SELECT * FROM direct_purchased WHERE AssetNo = '%s'",asset_no);
   try{
            rs = db.selectQuery(sql);
         
            while(rs.next())
            { DefaultTableModel model =  (DefaultTableModel) jTable1.getModel();
                 String AssetNo = rs.getString("AssetNo");
                 String AssetName = rs.getString("AssetName");
                 String date = rs.getString("purchased_date");
                 String category = "Direct Purchased";
                 String price = rs.getString("price");
                 
              Object[] content = {AssetNo, AssetName,category,date,price};
            
                 model.addRow(content);
  
            }  
    }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }                                        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnDispose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAssetList = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnAssemble = new javax.swing.JButton();
        btnDirect1 = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        cmbAssetNo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("DISPOSAL ASSETS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 0, 370, 100);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Asset No", "Asset Name", "Category", "Date", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(150, 360, 700, 150);

        btnDispose.setBackground(new java.awt.Color(102, 0, 102));
        btnDispose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDispose.setText("DISPOSE");
        btnDispose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisposeActionPerformed(evt);
            }
        });
        getContentPane().add(btnDispose);
        btnDispose.setBounds(380, 240, 170, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Select disposal Asset No.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 200, 310, 50);

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));
        jPanel1.setForeground(new java.awt.Color(102, 0, 204));

        btnAssetList.setBackground(new java.awt.Color(0, 153, 0));
        btnAssetList.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAssetList.setText("Asset List");
        btnAssetList.setActionCommand("");
        btnAssetList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssetListActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 153, 0));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAssemble.setBackground(new java.awt.Color(0, 153, 0));
        btnAssemble.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAssemble.setText("Assemble Asset");
        btnAssemble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssembleActionPerformed(evt);
            }
        });

        btnDirect1.setBackground(new java.awt.Color(0, 153, 0));
        btnDirect1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDirect1.setText("Direct Purchased");
        btnDirect1.setActionCommand("");
        btnDirect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirect1ActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(0, 153, 0));
        Logout.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnAssemble, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnDirect1)
                .addGap(59, 59, 59)
                .addComponent(btnAssetList, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnDirect1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnAssetList, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnAssemble, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 100, 1110, 40);

        cmbAssetNo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAssetNoItemStateChanged(evt);
            }
        });
        cmbAssetNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAssetNoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbAssetNo);
        cmbAssetNo.setBounds(140, 270, 130, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Beautifule-Nature-HD-Wallpaper.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -30, 1100, 660);

        setSize(new java.awt.Dimension(1117, 674));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssetListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssetListActionPerformed
        new AssetList().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAssetListActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAssembleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssembleActionPerformed
        new AssembleAsset().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAssembleActionPerformed

    private void btnDirect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirect1ActionPerformed
        new DirectPurchasedAsset().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDirect1ActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        new signup().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void cmbAssetNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAssetNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAssetNoActionPerformed

    private void cmbAssetNoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbAssetNoItemStateChanged
          DefaultTableModel mode2 =  (DefaultTableModel) jTable1.getModel();
                mode2.setRowCount(0);
     getDirectDetails();
         db.connection();
        ResultSet rs;  
        String asset_no = String.valueOf(cmbAssetNo.getSelectedItem());
        String sql = String.format("SELECT * FROM assemble_asset WHERE AssetNo = '%s'",asset_no);
   try{
            rs = db.selectQuery(sql);
            
            //  DefaultTableModel mode2 =  (DefaultTableModel) jTable1.getModel();
             //   mode2.setRowCount(0);
        
            while(rs.next())
            { DefaultTableModel model =  (DefaultTableModel) jTable1.getModel();
                 String AssetNo = rs.getString("AssetNo");
                 String AssetName = rs.getString("AssetName");
                 String date = rs.getString("DateOfAssemble");
                 String category = "Assemble Asset";
                 String price = rs.getString("totalPrice");
                 
              Object[] content = {AssetNo, AssetName,category,date,price};
            
                 model.addRow(content);
  
            }  
    }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_cmbAssetNoItemStateChanged

    private void btnDisposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisposeActionPerformed

          int dialogResult = JOptionPane.showConfirmDialog (null, "Are you Sure?  Do you want to Remove this Asset?");
        if(dialogResult == JOptionPane.YES_OPTION){
       
       int rows = jTable1.getRowCount();
       for(int row = 0; row<rows; row++){
    
           String assetType = (String)jTable1.getValueAt(row, 2);
           String assetNo = (String)jTable1.getValueAt(row, 0);
             if(assetType=="Assemble Asset"){
       String sql = String.format("DELETE FROM assemble_asset WHERE AssetNo = '%s'",assetNo);
        db.connection();
        int i = db.updateQuery(sql);
       if(i>0){
            JOptionPane.showMessageDialog(null, "Data Removed sucessfuly");
         DefaultTableModel mode2 =  (DefaultTableModel) jTable1.getModel();
        mode2.setRowCount(0);
       
       }
        else
       {JOptionPane.showMessageDialog(null, "Data not Removed");}
        
       }
             
       if(assetType=="Direct Purchased"){
        String sql = String.format("DELETE FROM direct_purchased WHERE AssetNo = '%s'",assetNo);
        db.connection();
        int i = db.updateQuery(sql);
       if(i>0){
            JOptionPane.showMessageDialog(null, "Data Removed sucessfuly");
         DefaultTableModel mode2 =  (DefaultTableModel) jTable1.getModel();
        mode2.setRowCount(0);
       
       }
        else
       {JOptionPane.showMessageDialog(null, "Data not Removed");}
       
       
       }
       
       }
   // JOptionPane.showMessageDialog(null,"Are you Sure?  Do you want to Remove this Asset? ");
       
        }  
       
    }//GEN-LAST:event_btnDisposeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dispose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dispose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dispose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dispose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dispose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton btnAssemble;
    private javax.swing.JButton btnAssetList;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDirect1;
    private javax.swing.JButton btnDispose;
    private javax.swing.JComboBox cmbAssetNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
