import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.Vector;
import MyClasses.Database;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import java.lang.NullPointerException;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class EditAssetList extends javax.swing.JFrame {
                       Database db = new Database();
    /**
     * Creates new form EditAssetList
     */
    public EditAssetList() {
        initComponents();
        showDirectAsset();
        showAssembleAsset();
         Date();
    }

     public void showDirectAsset(){
    
         try  { db.connection();   
          ResultSet rs1;
    String sql = "SELECT AssetNo,AssetName,purchased_date,Life_Time,price FROM direct_purchased";
     rs1 = db.selectQuery(sql);
 
        
    while(rs1.next())
        
    {  String AssetNo = rs1.getString("AssetNo");
       String AssetName = rs1.getString("AssetName");
       String PurchasedDate = rs1.getString("purchased_date");
       String price = rs1.getString("price");
       String category = "Direct purchased";
       String lifeTime = rs1.getString("Life_Time");
       
       
       Object[] content = {AssetNo,AssetName,PurchasedDate,category,lifeTime,price};
       
       DefaultTableModel model =  (DefaultTableModel) JTable1.getModel();
       
       model.addRow(content);
      
    }}
       
  catch(Exception e){
  JOptionPane.showMessageDialog(null, e.getMessage());
  
     }
      }
     
      public void showAssembleAsset(){
    
         try{  db.connection();   
     ResultSet rs1;
    String sql = "SELECT AssetNo,AssetName,DateOfAssemble,Life_Time,totalPrice FROM assemble_asset";
     rs1 = db.selectQuery(sql);
 
        
    while(rs1.next())                           
    {  String AssetNo = rs1.getString("AssetNo");
       String AssetName = rs1.getString("AssetName");
       String AssembledDate = rs1.getString("DateOfAssemble");
       String category = "Assembled Asset";
       String lifeTime = rs1.getString("Life_Time");
       String totPrice = rs1.getString("totalPrice");
       
       Object[] content = {AssetNo,AssetName,AssembledDate,category,lifeTime,totPrice};
       DefaultTableModel model =  (DefaultTableModel) JTable1.getModel();
       model.addRow(content);
    
    
      }
    
  }
  catch(Exception e){
  JOptionPane.showMessageDialog(null, e.getMessage());
  
     }
      }
      
       public void Date(){
         int rows = JTable1.getRowCount();
       for(int row = 0; row<rows; row++){
       String pattern = "yyyy-MM-30";
       SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
       String date = simpleDateFormat.format(new Date());
       
       DefaultTableModel model =  (DefaultTableModel) JTable1.getModel();
        model.setValueAt(date, row, 6);
       }
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTable1 = new javax.swing.JTable();
        btnCalDep = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        txtAssetNo = new javax.swing.JTextField();
        txtAssetName = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtCategory = new javax.swing.JTextField();
        txtLifeTime = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        JTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AssetNo ", "AssetName", "Date", "Category", "Life Time", "Price", "Depreciate Date", "Depreciate Amt"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Long.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Long.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 140, 740, 440);

        btnCalDep.setBackground(new java.awt.Color(102, 102, 102));
        btnCalDep.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnCalDep.setText("Calculate Depreciate");
        btnCalDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalDepActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalDep);
        btnCalDep.setBounds(240, 60, 190, 60);

        btnUpdate.setBackground(new java.awt.Color(102, 102, 102));
        btnUpdate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(530, 60, 150, 50);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("DISPOSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(770, 60, 160, 50);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 60, 120, 50);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Price");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(780, 410, 70, 30);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Asset Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(780, 210, 110, 30);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Date");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(780, 260, 70, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Category");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(780, 310, 80, 30);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Lfe Time");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(780, 360, 90, 30);
        getContentPane().add(txtPrice);
        txtPrice.setBounds(910, 410, 110, 30);

        txtAssetNo.setEditable(false);
        getContentPane().add(txtAssetNo);
        txtAssetNo.setBounds(910, 160, 110, 30);
        getContentPane().add(txtAssetName);
        txtAssetName.setBounds(910, 210, 110, 30);
        getContentPane().add(txtDate);
        txtDate.setBounds(910, 260, 110, 30);

        txtCategory.setEditable(false);
        getContentPane().add(txtCategory);
        txtCategory.setBounds(910, 310, 110, 30);
        getContentPane().add(txtLifeTime);
        txtLifeTime.setBounds(910, 360, 110, 30);

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("AssetNo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(770, 150, 260, 350);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Beautifule-Nature-HD-Wallpaper.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1, 0, 1210, 660);

        setSize(new java.awt.Dimension(1230, 709));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalDepActionPerformed
        DefaultTableModel model =  (DefaultTableModel) JTable1.getModel();
        //  SimpleDateFormat format = new  SimpleDateFormat("yyyy-MM-dd");
        try{

            Date d1 = null;
            Date d2 = null;
            int selectedrowIndex =  JTable1.getSelectedRow();

            // String id = model.getValueAt(selectedrowIndex, 6).toString();
            String price =  (String) model.getValueAt(selectedrowIndex, 5);
            double pricei = Double.parseDouble(price);
            String date =  (String)model.getValueAt(selectedrowIndex, 2);
            String Depdate = (String)model.getValueAt(selectedrowIndex, 6);

            DateFormat formatter;
            Date dd1;
            Date dd2;
            formatter = new SimpleDateFormat("yyyy-MM-dd");

            dd1 = (Date)formatter.parse(date);
            dd2 = (Date)formatter.parse(Depdate);
            //  JOptionPane.showMessageDialog(null,dd2);
            //    long ddd1 = dd1.getDate();
            //   long ddd2 = dd2.getDate();

            //    d1 = format.parse(format.format(date));
            //    d2 = format.parse(format.format(Depdate));
            long diff = dd2.getTime() - dd1.getTime();

            long sec = diff / 1000 % 60;
            long min = diff/(60*1000) % 60;
            long hours = diff /(60*60*1000);
            long days = hours/24;
            long months = days/30;
            JOptionPane.showMessageDialog(null,months);

            //int dated = Integer.parseInt(date);
            //  int datei = Integer.parseInt(date);
            //dd  String Depdate = (String) model.getValueAt(selectedrowIndex, 6);
            // long Depdated = Date.parse(Depdate);
            //ddint Depdatei = Integer.parseInt(Depdate);
            //dd  long months = (Depdatei - dated);
            //ddJOptionPane.showMessageDialog(null,months);

            double amt = 0.0;
            double tot = 0.0;

            amt = pricei/10*0.010;
            tot = tot + amt;
            // JOptionPane.showMessageDialog(null,tot);
            model.setValueAt(tot, selectedrowIndex, 7);

        }
        catch(Exception e)
        { JOptionPane.showMessageDialog(this,e.getMessage());

        }

    }//GEN-LAST:event_btnCalDepActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        DefaultTableModel model =  (DefaultTableModel) JTable1.getModel();
        int selectedrowIndex =  JTable1.getSelectedRow();

        
        String AssetNo =  txtAssetNo.getText();
        String AssetName =  txtAssetName.getText();
        String date =  txtDate.getText();
        String category = txtCategory.getText();
        String lifetime = txtLifeTime.getText();
        String price =  txtPrice.getText();
        
         String categoryi = (String) model.getValueAt(selectedrowIndex, 3);
       //  if(){}
        
         if(categoryi=="Direct purchased"){
             String sql = String.format("UPDATE direct_purchased SET AssetName = '%s', category = '%s', price = '%s', purchased_date = '%s', Life_Time = '%s'  WHERE AssetNo = '%s' ",AssetName,category
              , price,date,lifetime,AssetNo);
   
           int i = db.updateQuery(sql);
        if(i>0)
            JOptionPane.showMessageDialog(null, "Data Updated sucessfuly");
        else
          JOptionPane.showMessageDialog(null, "Data not Updated");
           }
           
          else if(categoryi=="Assembled Asset"){
                     txtPrice.setEditable(false);
                     
                   String sql = String.format("UPDATE assemble_asset SET AssetName = '%s', DateOfAssemble = '%s', Life_Time = '%s', totalPrice = '%s'  WHERE AssetNo = '%s' ",AssetName
              , date,lifetime,price,AssetNo);
   
           int i = db.updateQuery(sql);
        if(i>0)
            JOptionPane.showMessageDialog(null, "Data Updated sucessfuly");
        else
          JOptionPane.showMessageDialog(null, "Data not Updated");
           }  
                    

        model.setValueAt( AssetNo, selectedrowIndex, 0);
        model.setValueAt(AssetName, selectedrowIndex, 1);
        model.setValueAt(date, selectedrowIndex, 2);
        model.setValueAt(category, selectedrowIndex, 3);
        model.setValueAt(lifetime , selectedrowIndex, 4);
        model.setValueAt(price, selectedrowIndex, 5);
        
      
              
   //  else{
             
   //     JOptionPane.showMessageDialog(null, "you selected direct purchased  SUCCESSFULLY");
    //    }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable1MouseClicked
         DefaultTableModel model =  (DefaultTableModel) JTable1.getModel();
        int selectedrowIndex =  JTable1.getSelectedRow();
        
         String AssetNo = (String) model.getValueAt(selectedrowIndex, 0);
        String AssetNAme = (String) model.getValueAt(selectedrowIndex, 1);
        String date = (String) model.getValueAt(selectedrowIndex, 2);
        String category = (String) model.getValueAt(selectedrowIndex, 3);
        String lifetime = (String) model.getValueAt(selectedrowIndex, 4);
        String price = (String) model.getValueAt(selectedrowIndex, 5);
        
        if(category=="Assembled Asset")
        {  txtPrice.setEditable(false);
         }
        else{
        txtPrice.setEditable(true);
        }
        txtAssetNo.setText(AssetNo);
        txtAssetName.setText(AssetNAme);
        txtDate.setText(date);
        txtCategory.setText(category);
        txtLifeTime.setText(lifetime);
        txtPrice.setText(price);
    }//GEN-LAST:event_JTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      new dispose().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAssetList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAssetList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAssetList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAssetList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAssetList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable JTable1;
    private javax.swing.JButton btnCalDep;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAssetName;
    private javax.swing.JTextField txtAssetNo;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtLifeTime;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
