import MyClasses.*;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class RegisterForm extends javax.swing.JFrame {
    
    Database db = new Database();

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextUname = new javax.swing.JTextField();
        TextID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TextLname = new javax.swing.JTextField();
        jLabelRegister = new javax.swing.JLabel();
        Rpassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        TextFname = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();
        RegisterButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        RbAdmin = new javax.swing.JRadioButton();
        RbUser = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_exit2 = new javax.swing.JLabel();
        jLabel_exit3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("        Log ID:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(175, 50, 87, 23);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("    Retype Password:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(112, 262, 150, 23);

        TextUname.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        TextUname.setForeground(new java.awt.Color(51, 51, 51));
        TextUname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPanel2.add(TextUname);
        TextUname.setBounds(268, 180, 294, 23);

        TextID.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        TextID.setForeground(new java.awt.Color(51, 51, 51));
        TextID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPanel2.add(TextID);
        TextID.setBounds(268, 50, 294, 23);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Last Name:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(178, 132, 84, 23);

        TextLname.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        TextLname.setForeground(new java.awt.Color(51, 51, 51));
        TextLname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPanel2.add(TextLname);
        TextLname.setBounds(268, 132, 294, 23);

        jLabelRegister.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelRegister.setForeground(new java.awt.Color(0, 153, 255));
        jLabelRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegister.setText("Clik Here to Login");
        jLabelRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegisterMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelRegister);
        jLabelRegister.setBounds(304, 425, 158, 25);

        Rpassword.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Rpassword.setForeground(new java.awt.Color(51, 51, 51));
        Rpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Rpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RpasswordActionPerformed(evt);
            }
        });
        jPanel2.add(Rpassword);
        Rpassword.setBounds(268, 263, 294, 23);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Username:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(180, 180, 82, 23);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText(" Password:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(180, 221, 81, 23);

        Password.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(51, 51, 51));
        Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        jPanel2.add(Password);
        Password.setBounds(268, 222, 294, 23);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("First Name:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(177, 91, 85, 23);

        TextFname.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        TextFname.setForeground(new java.awt.Color(51, 51, 51));
        TextFname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPanel2.add(TextFname);
        TextFname.setBounds(268, 91, 294, 23);

        BackButton.setBackground(new java.awt.Color(0, 102, 153));
        BackButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        BackButton.setForeground(new java.awt.Color(51, 51, 51));
        BackButton.setText("Back");
        BackButton.setBorder(null);
        BackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel2.add(BackButton);
        BackButton.setBounds(19, 367, 110, 40);

        RegisterButton.setBackground(new java.awt.Color(0, 102, 153));
        RegisterButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(51, 51, 51));
        RegisterButton.setText("Register");
        RegisterButton.setBorder(null);
        RegisterButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        jPanel2.add(RegisterButton);
        RegisterButton.setBounds(745, 367, 110, 40);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("    Register Type:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(140, 305, 122, 23);

        buttonGroup1.add(RbAdmin);
        RbAdmin.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        RbAdmin.setForeground(new java.awt.Color(51, 51, 51));
        RbAdmin.setText("Asset Manager");
        RbAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RbAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbAdminActionPerformed(evt);
            }
        });
        jPanel2.add(RbAdmin);
        RbAdmin.setBounds(278, 304, 139, 25);

        buttonGroup1.add(RbUser);
        RbUser.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        RbUser.setForeground(new java.awt.Color(51, 51, 51));
        RbUser.setSelected(true);
        RbUser.setText("Employee");
        RbUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RbUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbUserActionPerformed(evt);
            }
        });
        jPanel2.add(RbUser);
        RbUser.setBounds(461, 304, 101, 25);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 80, 890, 470);

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Register Form");

        jLabel_exit2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_exit2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_exit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_exit2.setText("X");
        jLabel_exit2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_exit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exit2MouseClicked(evt);
            }
        });

        jLabel_exit3.setBackground(new java.awt.Color(51, 0, 153));
        jLabel_exit3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_exit3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_exit3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_exit3.setText("-");
        jLabel_exit3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_exit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exit3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(345, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233)
                .addComponent(jLabel_exit3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_exit2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel_exit3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel_exit2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 890, 70);

        setSize(new java.awt.Dimension(908, 594));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegisterMouseClicked
        // TODO add your handling code here:
        signup s = new signup();
        s.setVisible(true);
        s.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabelRegisterMouseClicked

    private void RpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RpasswordActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        this.hide();
        admin a = new admin();
        a.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
        db.connection();
    
        
        String id = TextID.getText();
        String Fname = TextFname.getText();
        String Lname = TextLname.getText();
        String Uname = TextUname.getText();
        String pwd =  Password.getText();
        String Rpwd = Rpassword.getText();
        String RType = "Asset Manager";
        if(RbUser.isSelected())
        {
            RType = "Employee";
          }
        
        if(TextID.getText().equals(""))
           { JOptionPane.showMessageDialog(null,"Please enter Login ID ");
         }
                
         if(TextFname.getText().equals(""))
           { JOptionPane.showMessageDialog(null,"Please enter your first name ");
         }
          else if((!(TextFname.getText().trim().matches("[a-zA-z,]+"))))
          {  JOptionPane.showMessageDialog(null,"First Name should be letters only.");} 
         
         
           if(TextLname.getText().equals(""))
           { JOptionPane.showMessageDialog(null,"Please enter your Last name ");
         }
           else if((!(TextLname.getText().trim().matches("[a-zA-z,]+"))))
          {  JOptionPane.showMessageDialog(null,"Last Name should be letters only.");} 
         
            else if(TextUname.getText().equals(""))
         { JOptionPane.showMessageDialog(null,"Please enter your username");
         }
           
          else if(Password.getText().equals(""))
         { JOptionPane.showMessageDialog(null,"Please enter password");
            
         }
           else if(Rpassword.getText().equals(""))
         { JOptionPane.showMessageDialog(null,"Please enter password again");
            
         }
           else if(Rpassword.getText().equals(Password.getText()))
         { JOptionPane.showMessageDialog(null,"Password should be same");
            
         }
          
           
            
            
        
          else{
        String sql = String.format("INSERT INTO user(loginID,FirstName,LastName,username,password,RegType)VALUES('%s','%s','%s','%s','%s','%s')"
                ,id,Fname,Lname,Uname,pwd,RType );
         
         int i = db.updateQuery(sql);
         if(i>0){
             
             
             
       JOptionPane.showMessageDialog(null, "Data added sucessfuly");
         TextFname.setText(null);
         TextLname.setText(null);
         TextUname.setText(null);
         Password.setText(null);
         Rpassword.setText(null);
        
          TextID.setText(null);
         RbAdmin.setSelected(false);
        RbUser.setSelected(false);
         }   
        {new signup().setVisible(true);
           this.dispose(); }
          }
        RbAdmin.setSelected(false);
        RbUser.setSelected(false);
        
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void RbAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbAdminActionPerformed
        // TODO add your handling code here:
        if(RbAdmin.isSelected())
        RbUser.setSelected(false);
    }//GEN-LAST:event_RbAdminActionPerformed

    private void RbUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbUserActionPerformed
        // TODO add your handling code here:
        if(RbUser.isSelected())
        RbAdmin.setSelected(false);
    }//GEN-LAST:event_RbUserActionPerformed

    private void jLabel_exit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exit2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel_exit2MouseClicked

    private void jLabel_exit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exit3MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_exit3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JPasswordField Password;
    private javax.swing.JRadioButton RbAdmin;
    private javax.swing.JRadioButton RbUser;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JPasswordField Rpassword;
    private javax.swing.JTextField TextFname;
    private javax.swing.JTextField TextID;
    private javax.swing.JTextField TextLname;
    private javax.swing.JTextField TextUname;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelRegister;
    private javax.swing.JLabel jLabel_exit2;
    private javax.swing.JLabel jLabel_exit3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
