import MyClasses.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class workingProgress extends javax.swing.JFrame {
            Database db = new Database();
            int value;
            
    /**       
     * Creates new form workingProgress
     */
    public workingProgress(String A,String B,String C,String D) {
        initComponents();
        getWrkingProgNo();
        loadAssetNo();
     
        txtAssetNo.setText(A); 
        txtAssetName.setText(B);
        txtCategory.setText(C);
        txtLifeTime.setText(D);
       
        
        int value = 0;  
       
        
    }
     public workingProgress() {
        initComponents();   
        getWrkingProgNo();
       loadAssetNo();
        int value = 0; 
    
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jFrame1 = new javax.swing.JFrame();
        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog2 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog3 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog4 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog5 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog6 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog7 = new datechooser.beans.DateChooserDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtAssetNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        txtAssetName = new javax.swing.JTextField();
        txtDate = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMaterialDetails = new javax.swing.JTextPane();
        jLabel12 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        DtChsrHoldDate = new com.toedter.calendar.JDateChooser();
        txtPrice = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtwrkngChrgs = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        txtLifeTime = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cmbAssetNo = new javax.swing.JComboBox();
        btnUpdateWrkngPrgrss = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAddAssetList = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnAssetList = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnAssemble = new javax.swing.JButton();
        btnDirect1 = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtTotPrice = new javax.swing.JTextField();
        jToolBar17 = new javax.swing.JToolBar();
        jToolBar18 = new javax.swing.JToolBar();
        jToolBar19 = new javax.swing.JToolBar();
        jToolBar20 = new javax.swing.JToolBar();
        jToolBar21 = new javax.swing.JToolBar();
        jToolBar22 = new javax.swing.JToolBar();
        jToolBar23 = new javax.swing.JToolBar();
        jToolBar24 = new javax.swing.JToolBar();
        jToolBar25 = new javax.swing.JToolBar();
        jToolBar26 = new javax.swing.JToolBar();
        jToolBar27 = new javax.swing.JToolBar();
        jToolBar28 = new javax.swing.JToolBar();
        jToolBar29 = new javax.swing.JToolBar();
        jToolBar30 = new javax.swing.JToolBar();
        jToolBar31 = new javax.swing.JToolBar();
        jToolBar32 = new javax.swing.JToolBar();
        jPanel4 = new javax.swing.JPanel();
        ckhComplete = new javax.swing.JCheckBox();
        ckhNotComplete = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        dateChooserDialog6.setNothingAllowed(false);

        dateChooserDialog7.setNothingAllowed(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("Working Progress");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(420, -10, 350, 90);

        jPanel2.setBackground(new java.awt.Color(255, 153, 255));
        jPanel2.setLayout(null);
        jPanel2.add(txtAssetNo);
        txtAssetNo.setBounds(150, 120, 110, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Life Time");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(450, 110, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Last Hold Date");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(430, 170, 130, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Price");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(690, 240, 50, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Asset Nos.");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(450, 10, 100, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Asset No");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 120, 80, 30);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(150, 20, 240, 30);
        jPanel2.add(txtAssetName);
        txtAssetName.setBounds(150, 70, 240, 30);
        jPanel2.add(txtDate);
        txtDate.setBounds(150, 170, 260, 40);

        jScrollPane2.setViewportView(txtMaterialDetails);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(150, 230, 260, 60);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Working Charges");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, 320, 150, 20);
        jPanel2.add(txtQty);
        txtQty.setBounds(500, 240, 160, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Quantity");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(420, 240, 80, 20);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(280, 400, 130, 60);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Staring Date");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 170, 110, 30);
        jPanel2.add(DtChsrHoldDate);
        DtChsrHoldDate.setBounds(560, 170, 240, 40);

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        jPanel2.add(txtPrice);
        txtPrice.setBounds(740, 240, 150, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Material Details");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 240, 120, 20);
        jPanel2.add(txtwrkngChrgs);
        txtwrkngChrgs.setBounds(150, 320, 250, 40);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Asset Name");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(10, 70, 100, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Category");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(450, 60, 100, 30);

        txtCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoryActionPerformed(evt);
            }
        });
        jPanel2.add(txtCategory);
        txtCategory.setBounds(560, 60, 170, 30);
        jPanel2.add(txtLifeTime);
        txtLifeTime.setBounds(560, 110, 170, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("prog.No");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(10, 10, 70, 30);

        cmbAssetNo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAssetNoItemStateChanged(evt);
            }
        });
        jPanel2.add(cmbAssetNo);
        cmbAssetNo.setBounds(560, 10, 240, 30);

        btnUpdateWrkngPrgrss.setBackground(new java.awt.Color(102, 102, 102));
        btnUpdateWrkngPrgrss.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnUpdateWrkngPrgrss.setText("Update New Added Details");
        btnUpdateWrkngPrgrss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateWrkngPrgrssActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdateWrkngPrgrss);
        btnUpdateWrkngPrgrss.setBounds(540, 400, 360, 60);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 140, 910, 480);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Asset No", "Staring Date", "Hold Date", "Material Details", "Quantity", "Price", "Working Charges"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(940, 140, 600, 190);

        btnAddAssetList.setBackground(new java.awt.Color(102, 102, 102));
        btnAddAssetList.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnAddAssetList.setText("Add to the Assemble Asset List");
        btnAddAssetList.setActionCommand("Add to the Asset List");
        btnAddAssetList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAssetListActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddAssetList);
        btnAddAssetList.setBounds(1130, 690, 400, 110);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setForeground(new java.awt.Color(102, 0, 204));

        btnAssetList.setBackground(new java.awt.Color(0, 153, 0));
        btnAssetList.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAssetList.setText("Asset List");
        btnAssetList.setActionCommand("");
        btnAssetList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssetListActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 153, 0));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAssemble.setBackground(new java.awt.Color(0, 153, 0));
        btnAssemble.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAssemble.setText("Assemble Asset");
        btnAssemble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssembleActionPerformed(evt);
            }
        });

        btnDirect1.setBackground(new java.awt.Color(0, 153, 0));
        btnDirect1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDirect1.setText("Direct Purchased");
        btnDirect1.setActionCommand("");
        btnDirect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirect1ActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(0, 153, 0));
        Logout.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137)
                .addComponent(btnAssemble, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239)
                .addComponent(btnDirect1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                .addComponent(btnAssetList, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnDirect1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnAssetList, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnAssemble, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 80, 1550, 40);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(jLabel9.getFont().deriveFont(jLabel9.getFont().getStyle() | java.awt.Font.BOLD, jLabel9.getFont().getSize()+22));
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("Total Price");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1170, 330, 190, 60);
        getContentPane().add(txtTotPrice);
        txtTotPrice.setBounds(1380, 340, 160, 40);

        jToolBar17.setRollover(true);

        jToolBar18.setRollover(true);
        jToolBar17.add(jToolBar18);

        jToolBar19.setRollover(true);

        jToolBar20.setRollover(true);
        jToolBar19.add(jToolBar20);

        jToolBar17.add(jToolBar19);

        jToolBar21.setRollover(true);

        jToolBar22.setRollover(true);
        jToolBar21.add(jToolBar22);

        jToolBar23.setRollover(true);

        jToolBar24.setRollover(true);
        jToolBar23.add(jToolBar24);

        jToolBar21.add(jToolBar23);

        jToolBar17.add(jToolBar21);

        jToolBar25.setRollover(true);

        jToolBar26.setRollover(true);
        jToolBar25.add(jToolBar26);

        jToolBar27.setRollover(true);

        jToolBar28.setRollover(true);
        jToolBar27.add(jToolBar28);

        jToolBar25.add(jToolBar27);

        jToolBar29.setRollover(true);

        jToolBar30.setRollover(true);
        jToolBar29.add(jToolBar30);

        jToolBar31.setRollover(true);

        jToolBar32.setRollover(true);
        jToolBar31.add(jToolBar32);

        jToolBar29.add(jToolBar31);

        jToolBar25.add(jToolBar29);

        jToolBar17.add(jToolBar25);

        getContentPane().add(jToolBar17);
        jToolBar17.setBounds(10, 140, 10, 650);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(null);

        ckhComplete.setText("COMPLETE");
        jPanel4.add(ckhComplete);
        ckhComplete.setBounds(490, 60, 111, 29);

        ckhNotComplete.setText("NOT COMPLETE");
        jPanel4.add(ckhNotComplete);
        ckhNotComplete.setBounds(620, 60, 149, 29);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane3);
        jScrollPane3.setBounds(10, 50, 460, 96);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 0, 0));
        jLabel17.setText("Present Situation of the Asset");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(20, 10, 350, 40);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 35)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 0, 0));
        jLabel18.setText("Status : ");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(490, 10, 180, 40);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(20, 620, 910, 170);

        btnUpdate.setBackground(new java.awt.Color(102, 102, 102));
        btnUpdate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnUpdate.setText("UPDATE TABLE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(940, 340, 180, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background-nature-raindrop-world-wallpapers-78634.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-10, 0, 1560, 890);

        setSize(new java.awt.Dimension(1562, 937));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       //Add details to the table
        getWrkingProgNo();
        
       double Totprice = 0;
      
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
       String Startingdate = sdf.format( txtDate.getDate());
       String holdDate = sdf.format( DtChsrHoldDate.getDate());
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        model.addRow(new Object[]{txtAssetNo.getText(),Startingdate,holdDate,
                    txtMaterialDetails.getText(),txtQty.getText(), txtPrice.getText(),txtwrkngChrgs.getText()});
        
        int rows1 = jTable1.getRowCount();
        for(int row1 = 0; row1<rows1; row1++)
        { String price = (String)jTable1.getValueAt(row1, 5);
        double getpricei= Double.parseDouble(price);
        
        String wrkngchgs = (String)jTable1.getValueAt(row1, 6);
        double wrkgi = Double.parseDouble(wrkngchgs);
        
        Totprice= getpricei + Totprice+wrkgi;
        txtTotPrice.setText(String.valueOf(Totprice));
        
      //  txtDate.setText(null);
        txtMaterialDetails.setText(null);
        txtPrice.setText(null);
        txtQty.setText(null);
        txtwrkngChrgs.setText(null);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAddAssetListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAssetListActionPerformed

        
        db.connection();
              String total=txtTotPrice.getText(); 
              String AssetNo= txtAssetNo.getText();
             String AssetName =  txtAssetName.getText();
             String Category = txtCategory.getText();
             String LifeTime = txtLifeTime.getText();
             String PrgrsNo = jTextField2.getText();
          SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
       String Startingdate = sdf.format( txtDate.getDate());
       String holdDate = sdf.format( DtChsrHoldDate.getDate());
       
   if(ckhNotComplete.isSelected()){
     
       try{
           
      
         // String wrkngChrgs = txtwrkngChrgs.getText();
          String status = jTextArea1.getText();
             
           
      String sql = "INSERT INTO working_progress(AssetNo,AssetName,category,LifeTime,Startingdate,HoldDate,SatusOfTheAsset,totprice) VALUES('"+AssetNo+"','"+AssetName+"','"+ Category+"','"+LifeTime+"','"+Startingdate+"','"+holdDate+"','"+status+"','"+total+"')";
       int i= db.updateQuery(sql);
       
        if(i>0)
        { JOptionPane.showMessageDialog(null,"Successfully added!");
          
       
        }
        else
        { JOptionPane.showMessageDialog(null,"Not entered");
        }
       }
         catch(Exception e)
       { JOptionPane.showMessageDialog(this,e.getMessage());
       
       }
       /////////////////////ADD MATERIAL DETAILS//////////////
       int rows = jTable1.getRowCount();
       for(int row = 0; row<rows; row++)
     { 
       String MaterialDet = (String)jTable1.getValueAt(row, 3);
       String qty = (String)jTable1.getValueAt(row, 4);
       String price = (String)jTable1.getValueAt(row, 5);
       
        String sql2 = "INSERT INTO material_master_table(AssetNo,wrkngPrgrsNO,materialName,Qty,price) VALUES('"+AssetNo+"','"+PrgrsNo+"','"+MaterialDet+"','"+qty+"','"+price+"')";
       int i= db.updateQuery(sql2);
     if(i>0)
        { JOptionPane.showMessageDialog(null,"Successfully Updated Material Details");
           jTextArea1.setText(null);
           txtMaterialDetails.setText(null);
           txtQty.setText(null);
           txtPrice.setText(null);
           txtwrkngChrgs.setText(null);
        }
        else
        { JOptionPane.showMessageDialog(null,"Not enteredMaterial Details" );
        }
     
     }
       
       
       
   }
   else if(ckhComplete.isSelected()){
    String CategoryA = "Assembled Asset";
   String sql2 = "INSERT INTO assemble_asset(AssetNo,AssetName,category,DateOfAssemble,Life_Time,totalPrice) VALUES('"+AssetNo+"','"+AssetName+"','"+CategoryA+"','"+holdDate+"','"+LifeTime+"','"+total+"')";
    int i= db.updateQuery(sql2);
     if(i>0)
        { JOptionPane.showMessageDialog(null,"Successfully Updated Assembled AssetList");
          
        }
        else
        { JOptionPane.showMessageDialog(null,"Not Update Assembled AssetList" );
        }
   
   
     }
       
   else if(ckhComplete.isSelected() && ckhNotComplete.isSelected() )
   {
       JOptionPane.showMessageDialog(null,"Please Choose One State" );
     }
   
   else if(!ckhComplete.isSelected() && !ckhNotComplete.isSelected())
   {
        JOptionPane.showMessageDialog(null,"Please Choose a State" );
   
      }
   
 
       
      
    }//GEN-LAST:event_btnAddAssetListActionPerformed

    public  void getWrkingProgNo()
    {

          value = value + 1;
          String res = String.valueOf(value);
          jTextField2.setText(res);  
        
    }
    
     public void loadAssetNo()
    {
         ResultSet rs;
        db.connection();
         try {
            String sql = "SELECT AssetNo FROM working_progress";
            rs = db.selectQuery(sql);
        while (rs.next()) {
            String pat = rs.getString(1);
            cmbAssetNo.addItem(pat);
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e);
    }
    }
    
   
    
    private void btnAssetListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssetListActionPerformed
        new AssetList().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAssetListActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new AssembleAsset().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAssembleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssembleActionPerformed
        db.connection();
        
        
        
        new AssembleAsset().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAssembleActionPerformed

    private void btnDirect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirect1ActionPerformed
        new DirectPurchasedAsset().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDirect1ActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        new signup().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
      DefaultTableModel model =  (DefaultTableModel) jTable1.getModel();
       SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String Startdate = sdf.format( txtDate.getDate());
          String Holdtdate = sdf.format( DtChsrHoldDate.getDate());
        int selectedrowIndex =  jTable1.getSelectedRow();  
      
        
         String qty = txtQty.getText();
         String Matreialdetails = txtMaterialDetails.getText();
         String price = txtPrice.getText();
         String wrkngchgs = txtwrkngChrgs.getText();
         
          model.setValueAt(Startdate, selectedrowIndex, 1);
           model.setValueAt(Holdtdate, selectedrowIndex, 2);   
          model.setValueAt(qty, selectedrowIndex, 4);
          model.setValueAt(Matreialdetails, selectedrowIndex, 3);
          model.setValueAt(price, selectedrowIndex, 5);
             model.setValueAt(wrkngchgs, selectedrowIndex, 6);
         
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
          DefaultTableModel model =  (DefaultTableModel) jTable1.getModel();
        int selectedrowIndex =  jTable1.getSelectedRow();  
        
         String qty = (String) model.getValueAt(selectedrowIndex, 4);
        String Materialdetails = (String) model.getValueAt(selectedrowIndex, 3);
        String priceR = (String) model.getValueAt(selectedrowIndex, 5);
        String wrkgChrgs = (String) model.getValueAt(selectedrowIndex, 6);
        
        txtwrkngChrgs.setText(wrkgChrgs);
        txtMaterialDetails.setText(Materialdetails);
        txtPrice.setText(priceR);
        txtQty.setText(qty);
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void txtCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoryActionPerformed

    private void cmbAssetNoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbAssetNoItemStateChanged
         db.connection();
        ResultSet rs;
        String AssetNo = String.valueOf(cmbAssetNo.getSelectedItem());
        String sql = String.format("SELECT * FROM working_progress WHERE AssetNo = '%s'",AssetNo);
        try{
            rs = db.selectQuery(sql);
            while(rs.next())
            {
              txtAssetNo.setText(rs.getString("AssetNo"));
              txtAssetName.setText(rs.getString("AssetName"));
              txtCategory.setText(rs.getString("category"));
              txtLifeTime.setText(rs.getString("LifeTime"));
              txtDate.setDate(rs.getDate("Startingdate"));
              DtChsrHoldDate.setDate(rs.getDate("HoldDate"));
              jTextArea1.setText(rs.getString("SatusOfTheAsset"));
              txtTotPrice.setText(rs.getString("totprice"));
              
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_cmbAssetNoItemStateChanged

    private void btnUpdateWrkngPrgrssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateWrkngPrgrssActionPerformed
       ///////////UPDATE WORKING PROGRESS//////////////
        String total=txtTotPrice.getText(); 
              String AssetNo= txtAssetNo.getText();
             String AssetName =  txtAssetName.getText();
             String Category = txtCategory.getText();
             String LifeTime = txtLifeTime.getText();
             String PrgrsNo = jTextField2.getText();
          SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
       String Startingdate = sdf.format( txtDate.getDate());
       String holdDate = sdf.format( DtChsrHoldDate.getDate());
       String status = jTextArea1.getText();
       double Totprice = 0;
       
        int rows1 = jTable1.getRowCount();
        for(int row1 = 0; row1<rows1; row1++)
        { String priceA = (String)jTable1.getValueAt(row1, 5);
        double getpricei= Double.parseDouble(priceA);
        
        String wrkngchgs = (String)jTable1.getValueAt(row1, 6);
        double wrkgi = Double.parseDouble(wrkngchgs);
        
       // double txtTot = Double.parseDouble(total);
       try{  ResultSet rs;
         String sql3 = String.format("SELECT * FROM working_progress WHERE AssetNo = '%s'",AssetNo);
           rs = db.selectQuery(sql3);
           while(rs.next()){
           String txTot = rs.getString("totprice");
           double txTotD = Double.parseDouble(txTot);
       
        Totprice= (getpricei + Totprice + wrkgi);
        double NetTOT =  Totprice + txTotD;
        String PassTot = String.valueOf(NetTOT);
        //txtTotPrice.setText(String.valueOf(Totprice));
        
          String sql = String.format("UPDATE working_progress SET AssetName = '%s', category = '%s', LifeTime = '%s', Startingdate = '%s', HoldDate = '%s', SatusOfTheAsset = '%s', totprice = '%s' WHERE AssetNo = '%s' ",AssetName,Category
              ,LifeTime,Startingdate,holdDate,status,PassTot,AssetNo);
   
           int i = db.updateQuery(sql);
        if(i>0)
            JOptionPane.showMessageDialog(null, "Data Updated sucessfuly");
        else
          JOptionPane.showMessageDialog(null, "Data not Updated");
        }}
          catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
        }
        
        /////////ADD MATERIAL TABLE////////////
          int rows = jTable1.getRowCount();
       for(int row = 0; row<rows; row++)
     { 
       String MaterialDet = (String)jTable1.getValueAt(row, 3);
       String qty = (String)jTable1.getValueAt(row, 4);
       String price = (String)jTable1.getValueAt(row, 5);
       
        String sql3 = "INSERT INTO material_master_table(AssetNo,wrkngPrgrsNO,materialName,Qty,price) VALUES('"+AssetNo+"','"+PrgrsNo+"','"+MaterialDet+"','"+qty+"','"+price+"')";
        db.updateQuery(sql3);
     
         JOptionPane.showMessageDialog(null,"Successfully Updated Material Details");
     
     }   
       
        
        
    }//GEN-LAST:event_btnUpdateWrkngPrgrssActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(workingProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(workingProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(workingProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(workingProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new workingProgress().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DtChsrHoldDate;
    private javax.swing.JButton Logout;
    private javax.swing.JButton btnAddAssetList;
    private javax.swing.JButton btnAssemble;
    private javax.swing.JButton btnAssetList;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDirect1;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateWrkngPrgrss;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox ckhComplete;
    private javax.swing.JCheckBox ckhNotComplete;
    private javax.swing.JComboBox cmbAssetNo;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserDialog dateChooserDialog2;
    private datechooser.beans.DateChooserDialog dateChooserDialog3;
    private datechooser.beans.DateChooserDialog dateChooserDialog4;
    private datechooser.beans.DateChooserDialog dateChooserDialog5;
    private datechooser.beans.DateChooserDialog dateChooserDialog6;
    private datechooser.beans.DateChooserDialog dateChooserDialog7;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToolBar jToolBar17;
    private javax.swing.JToolBar jToolBar18;
    private javax.swing.JToolBar jToolBar19;
    private javax.swing.JToolBar jToolBar20;
    private javax.swing.JToolBar jToolBar21;
    private javax.swing.JToolBar jToolBar22;
    private javax.swing.JToolBar jToolBar23;
    private javax.swing.JToolBar jToolBar24;
    private javax.swing.JToolBar jToolBar25;
    private javax.swing.JToolBar jToolBar26;
    private javax.swing.JToolBar jToolBar27;
    private javax.swing.JToolBar jToolBar28;
    private javax.swing.JToolBar jToolBar29;
    private javax.swing.JToolBar jToolBar30;
    private javax.swing.JToolBar jToolBar31;
    private javax.swing.JToolBar jToolBar32;
    private javax.swing.JTextField txtAssetName;
    private javax.swing.JTextField txtAssetNo;
    private javax.swing.JTextField txtCategory;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtLifeTime;
    private javax.swing.JTextPane txtMaterialDetails;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtTotPrice;
    private javax.swing.JTextField txtwrkngChrgs;
    // End of variables declaration//GEN-END:variables
}
